### ISSUE TITLE
Additional outputs needed for encrypted_bucket

### ISSUE THREAD

**Issue by Vermyndax** [18F/cg-provision#316]
To use the encrypted_bucket module, we need to add additional outputs to write bucket policies against them outside the view of the module itself.

Needed in outputs.tf:

output "bucket_arn" {
  value = "${aws_s3_bucket.encrypted_bucket.arn}"
}

output "bucket_id" {
  value = "${aws_s3_bucket.encrypted_bucket.id}"
}

**Comment by jmcarp** [comment]
Our terraform modules aren't guaranteed to be stable, so I wouldn't recommend referencing them from your own configuration. This might be a rare case where copying and pasting is a better approach.
